### ISSUE TITLE
Missing README

### ISSUE THREAD

**Issue by glegrain** [thibthibaut/CompassPartout#1]
What is the purpose of this app?

**Comment by thibthibaut** [comment]
Haha let me fix this...

**Comment by guillaumeShare** [comment]
Thx ! ;)

Guillaume LEIGNIER

## *Mail: *leignier@ece.fr

JobServic'ECE - Trésorier
www.jobservice.ece.fr http://jobservice.ece.fr/

2016-05-30 10:49 GMT+02:00 thibthibaut notifications@github.com:

**Comment by thibthibaut** [comment]
C'est quoi cette vielle signature de mail Leignier ?
